// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD26lHMYT32_GPyA89mb7dWnjHTZuzmAc',
    appId: '1:206213649112:web:b8825de00ad66306ebbdad',
    messagingSenderId: '206213649112',
    projectId: 'scjrbb',
    authDomain: 'scjrbb.firebaseapp.com',
    storageBucket: 'scjrbb.appspot.com',
    measurementId: 'G-9BXC8VZ6TS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXH43SHHq2qHBJ9zKOhXjKAsuVvwDGFAw',
    appId: '1:206213649112:android:7184f322bed89574ebbdad',
    messagingSenderId: '206213649112',
    projectId: 'scjrbb',
    storageBucket: 'scjrbb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5rMUZ6Tt_9dLM68YZPKYf6LMdwIS94Wo',
    appId: '1:206213649112:ios:ca5142652e9a3a34ebbdad',
    messagingSenderId: '206213649112',
    projectId: 'scjrbb',
    storageBucket: 'scjrbb.appspot.com',
    androidClientId: '206213649112-al8fuorbrjl6vovusjn7164t4307gtrf.apps.googleusercontent.com',
    iosClientId: '206213649112-aacasuqeql8o2qa63i644o6csm009kmd.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobrbb',
  );
}
